#! /usr/bin/env python
# -*- coding: utf-8 -*-

import os

out = """# environment file
echo "Setting up %(environ)s environment"
echo ""

deactivate() {
    # reset the prompt
    if [ -n "$_OLD_PS1" ]; then
        PS1="$_OLD_PS1"
        export PS1
        unset _OLD_PS1
    fi

    # reset the path
    if [ -n "$_OLD_PATH" ]; then
        PATH="$_OLD_PATH"
        export PATH
        unset _OLD_PATH
    fi

    # Unset and change other stuff here if you wish
    
    # kill this function
    if [ ! "$1" = "keep" ]; then
        unset -f deactivate
    fi
}

# make sure we're good when entering the environment
deactivate keep

_OLD_PS1="$PS1"
_OLD_PATH="$PATH"

export PS1="(%(environ)s)$PS1"

# Add your own stuff below this line
"""


def main():
    pwd = os.getcwd()
    environ = os.path.basename(pwd)
    with open(os.path.join(pwd, '.env'), 'w') as f:
        f.write(out % {'environ': environ})


if __name__ == '__main__':
    main()
